version: "3"

services:
  topic_segmentation_worker:
    build: .
    environment:
      QUEUE_SERVER: "localhost:5672"
      FILES_SERVER: "localhost:3001"
      INPUT_QUEUE_NAME: "topic_segmentation_in"
      OUTPUT_QUEUE_NAME: "topic_segmentation_out"

    volumes:
      - /media/word2vec:/word2vec